/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.carreras.gui;

import beans.Carreras;
import beans.Corredores;
import beans.NuevosCorredores;
import interfaz.corredores.tablemodels.TableModelCarreras;
import interfaz.corredores.tablemodels.TableModelCorredores;
import interfaz.pantallaPrincipal;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import logica.logicaAplicacion;

/**
 *
 * @author Tony
 */
public class pantallaPrincipalCarreras extends javax.swing.JFrame {
      private TableRowSorter<TableModelCarreras> sorter;
    /**
     * Creates new form pantallaPrincipalCarreras
     */
    public pantallaPrincipalCarreras() {
        initComponents();
        rellenarTablaCarreras();
       
    
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCarreras = new javax.swing.JTable();
        jButtonFiltrar = new javax.swing.JButton();
        jTextFieldFiltrar = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCarreras = new javax.swing.JMenu();
        jCarrerasAlta = new javax.swing.JMenuItem();
        jBorrarCarrera = new javax.swing.JMenuItem();
        jModificarCarrera = new javax.swing.JMenuItem();
        jComenzarCarrera = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuCorredores = new javax.swing.JMenu();
        jAñadirCorredores = new javax.swing.JMenuItem();
        JAñadirNuevoCorredor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTableCarreras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableCarreras);

        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiltrarActionPerformed(evt);
            }
        });

        jMenuCarreras.setText("Carreras");

        jCarrerasAlta.setText("Añadir carrera");
        jCarrerasAlta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCarrerasAltaActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jCarrerasAlta);

        jBorrarCarrera.setText("Borrar carrera");
        jBorrarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarCarreraActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jBorrarCarrera);

        jModificarCarrera.setText("Modificar carrera");
        jModificarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jModificarCarreraActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jModificarCarrera);

        jComenzarCarrera.setText("Comenzar carrera");
        jComenzarCarrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComenzarCarreraActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jComenzarCarrera);

        jMenuSalir.setText("Salir a inicio");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuCarreras.add(jMenuSalir);

        jMenuBar1.add(jMenuCarreras);

        jMenuCorredores.setText("Corredores");

        jAñadirCorredores.setText("Añadir corredores");
        jAñadirCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAñadirCorredoresActionPerformed(evt);
            }
        });
        jMenuCorredores.add(jAñadirCorredores);

        JAñadirNuevoCorredor.setText("Añadir un nuevo corredor");
        JAñadirNuevoCorredor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JAñadirNuevoCorredorActionPerformed(evt);
            }
        });
        jMenuCorredores.add(JAñadirNuevoCorredor);

        jMenuBar1.add(jMenuCorredores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonFiltrar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFiltrar)
                    .addComponent(jTextFieldFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 115, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCarrerasAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCarrerasAltaActionPerformed
        FormularioAltaCarrera formulario=new FormularioAltaCarrera(this,true);
        formulario.setVisible(true);
        refrescarTabla();
        nuevoCorredor();
      
    }//GEN-LAST:event_jCarrerasAltaActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        pantallaPrincipal pantallaprincipal=new pantallaPrincipal();
        pantallaPrincipalCarreras pantalla=new pantallaPrincipalCarreras();
        pantallaprincipal.setVisible(true);
        pantalla.dispose();
        
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jComenzarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComenzarCarreraActionPerformed
      
    String resultado=JOptionPane.showInputDialog(this,"Introduce el nombre de la carrera a comenzar","Comenzar Carrera");
    
    PantallaTemporizador pantalla=new PantallaTemporizador();
    pantalla.comprobarNombre(resultado);
    pantalla.setVisible(true);
    
    }//GEN-LAST:event_jComenzarCarreraActionPerformed

    private void jAñadirCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAñadirCorredoresActionPerformed
       DefaultTableModel dtm=(DefaultTableModel)jTableCarreras.getModel();
       
     ArrayList<Carreras>listaCarreras=logicaAplicacion.getListaCarreras();

          
        
        
     
  JOptionPane.showMessageDialog(this, "Se importarán los corredores registrados y se generará un dorsal para cada uno de ellos","Añadir corredores",JOptionPane.INFORMATION_MESSAGE);
    
          for(Carreras c:listaCarreras){
         
            
            dtm.addColumn("Corredores",c.toArrayStringCorredores());
            
           dtm.addColumn("Dorsal",c.generarDorsales());
        
        
   
        }
          jTableCarreras.setModel(dtm);
    
  
    }//GEN-LAST:event_jAñadirCorredoresActionPerformed

    
        
    
    private void JAñadirNuevoCorredorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JAñadirNuevoCorredorActionPerformed
        FormularioAltaCorredor alta=new FormularioAltaCorredor(this,true);
        alta.setVisible(true);
        nuevoCorredor();
      
       
    }//GEN-LAST:event_JAñadirNuevoCorredorActionPerformed

    private void jBorrarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarCarreraActionPerformed
        int contador=0;
        ArrayList<Carreras>listaCarreras=logicaAplicacion.getListaCarreras();
        Iterator<Carreras>it=listaCarreras.iterator();
        DefaultTableModel dtm = (DefaultTableModel) jTableCarreras.getModel();
        String resultado= JOptionPane.showInputDialog(this,"Introduce el nombre de la carrera que deseas borrar","Borrar carrera");
       
         for(Carreras carrera:listaCarreras){
          
          if(resultado.equalsIgnoreCase(carrera.getNombre())){
            
             dtm.removeRow(contador);
              
            
          }
          else
              contador++;

      }
         
    }//GEN-LAST:event_jBorrarCarreraActionPerformed

    private void jModificarCarreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jModificarCarreraActionPerformed
         int contador=0;
        ArrayList<Carreras>listaCarreras=logicaAplicacion.getListaCarreras();
        Iterator<Carreras>it=listaCarreras.iterator();
        DefaultTableModel dtm = (DefaultTableModel) jTableCarreras.getModel();
        String resultado= JOptionPane.showInputDialog(this,"Introduce el nombre de la carrera que deseas borrar","Borrar carrera");
       
         for(Carreras carrera:listaCarreras){
          
          if(resultado.equalsIgnoreCase(carrera.getNombre())){
            
                  dtm.removeRow(contador); 
              
            
             String nombre=JOptionPane.showInputDialog(this,"Introduce el nuevo nombre del corredor");
            
             String fecha=JOptionPane.showInputDialog(this,"Introduce el nuevo nombre del corredor");
             String lugar=JOptionPane.showInputDialog(this,"Introduce el nuevo nombre del corredor");
             String numero=JOptionPane.showInputDialog(this,"Introduce el nuevo nombre del corredor");

             String  [] array=new String[4];
             
             array[0]=nombre;
             array[1]=fecha;
             array[2]=lugar;
             array[3]=numero;
             
             dtm.addRow(array);
             
             jTableCarreras.setModel(dtm);
              
            
          }
          else
              contador++;

      }
    }//GEN-LAST:event_jModificarCarreraActionPerformed

    private void jButtonFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiltrarActionPerformed
         RowFilter<TableModelCarreras,Integer> rf=RowFilter.regexFilter(jTextFieldFiltrar.getText(),0);
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_jButtonFiltrarActionPerformed

     private void rellenarTablaCarreras()
    {
        TableModelCarreras tma=new TableModelCarreras(logicaAplicacion.getListaCarreras());
      
        
        jTableCarreras.setModel(tma);
      sorter= new TableRowSorter<>(tma);
           jTableCarreras.setRowSorter(sorter);
           List<RowSorter.SortKey> sortkeys=new ArrayList<>();
           sortkeys.add(new RowSorter.SortKey(0,SortOrder.ASCENDING));
         sorter.setSortKeys(sortkeys);
    }

    private void refrescarTabla(){
        DefaultTableModel dtm=new DefaultTableModel();
   
        
        dtm.setColumnIdentifiers(new String[]{"Nombre","Fecha","Lugar","Número máximo de participantes"});
       
        
        ArrayList<Carreras>listaCarreras=logicaAplicacion.getListaCarreras();
        
        for(Carreras carrera:listaCarreras){
            
            
            dtm.addRow(carrera.toArrayString());
 
              
        }
        jTableCarreras.setModel(dtm);
       

    }
    
    private void nuevoCorredor(){
        
        ArrayList<NuevosCorredores> lista_nuevo=logicaAplicacion.getNueva_lista();
        
        DefaultTableModel dtm=(DefaultTableModel)jTableCarreras.getModel();
        
        for(NuevosCorredores nuevo:lista_nuevo){
            dtm.addColumn("Nuevo",nuevo.toArrayString());
        }
        
        jTableCarreras.setModel(dtm);
        
    }
        
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JAñadirNuevoCorredor;
    private javax.swing.JMenuItem jAñadirCorredores;
    private javax.swing.JMenuItem jBorrarCarrera;
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JMenuItem jCarrerasAlta;
    private javax.swing.JMenuItem jComenzarCarrera;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCarreras;
    private javax.swing.JMenu jMenuCorredores;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jModificarCarrera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCarreras;
    private javax.swing.JTextField jTextFieldFiltrar;
    // End of variables declaration//GEN-END:variables
}
